/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1232
-- password_profile_pure::add_to_blacklist
CREATE  FUNCTION "add_to_blacklist"(
	"password" TEXT, /* &str */
	"reason" TEXT /* core::option::Option<&str> */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_to_blacklist_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:810
-- password_profile_pure::check_password
CREATE  FUNCTION "check_password"(
	"username" TEXT, /* &str */
	"password" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'check_password_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1207
-- password_profile_pure::check_password_expiry
CREATE  FUNCTION "check_password_expiry"(
	"username" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'check_password_expiry_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1131
-- password_profile_pure::check_user_access
CREATE  FUNCTION "check_user_access"(
	"username" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'check_user_access_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1083
-- password_profile_pure::clear_login_attempts
CREATE  FUNCTION "clear_login_attempts"(
	"username" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'clear_login_attempts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1263
-- password_profile_pure::get_password_stats
CREATE  FUNCTION "get_password_stats"(
	"username" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_password_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:963
-- password_profile_pure::init_login_attempts_table
CREATE  FUNCTION "init_login_attempts_table"() RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'init_login_attempts_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1115
-- password_profile_pure::is_user_locked
CREATE  FUNCTION "is_user_locked"(
	"username" TEXT /* &str */
) RETURNS bool /* core::result::Result<bool, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'is_user_locked_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1014
-- password_profile_pure::record_failed_login
CREATE  FUNCTION "record_failed_login"(
	"username" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'record_failed_login_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1169
-- password_profile_pure::record_password_change
CREATE  FUNCTION "record_password_change"(
	"username" TEXT, /* &str */
	"new_password" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'record_password_change_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1251
-- password_profile_pure::remove_from_blacklist
CREATE  FUNCTION "remove_from_blacklist"(
	"password" TEXT /* &str */
) RETURNS TEXT /* core::result::Result<alloc::string::String, alloc::boxed::Box<dyn core::error::Error>> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_from_blacklist_wrapper';
/* </end connected objects> */

