# PostgreSQL password_profile Extension RPM Spec File
# Rust-based extension using pgrx
# BiSoft Information Technologies

%global pgmajorversion 17
%global pginstdir /usr/pgsql-%{pgmajorversion}
%global sname password_profile
%global pkgname password-profile

# Disable debug packages
%define debug_package %{nil}
%define _debugsource_template %{nil}

Summary:        PostgreSQL password profile management extension (Rust/pgrx)
Name:           %{pkgname}%{pgmajorversion}
Version:        0.0.0
Release:        1%{?dist}
License:        GPLv3
Group:          Applications/Databases
URL:            https://github.com/bisoftbilgi/bisoft-postgresql-toolkit

# Source tarball
Source0:        password_profile-%{version}.tar.gz

# Build requirements
BuildRequires:  postgresql%{pgmajorversion}-devel
BuildRequires:  gcc
BuildRequires:  clang
BuildRequires:  llvm
BuildRequires:  openssl-devel
BuildRequires:  pkgconfig
BuildRequires:  krb5-devel

# Runtime requirements
Requires:       postgresql%{pgmajorversion}-server

%description
The password_profile extension provides advanced password profile management
capabilities for PostgreSQL databases using Rust and pgrx framework.

Features:
- Password complexity enforcement
- Password history tracking
- Configurable password blacklists
- Account lockout policies
- High performance with Rust implementation

Developed by BiSoft Information Technologies.

%prep
%setup -q -n password_profile-%{version}

%build
# Set PostgreSQL environment
export PG_CONFIG=%{pginstdir}/bin/pg_config
export PATH=%{pginstdir}/bin:$PATH

# Ensure we have the correct pg_config
echo "Using PostgreSQL version:"
${PG_CONFIG} --version

# Install cargo-pgrx if not present in build environment
# Note: In production, this should be pre-installed in the build system
if ! cargo pgrx --version >/dev/null 2>&1; then
    echo "Installing cargo-pgrx..."
    cargo install --locked cargo-pgrx --version 0.16.1
fi

# Initialize pgrx for PostgreSQL 17
cargo pgrx init --pg%{pgmajorversion} ${PG_CONFIG}

# Build the extension
#export RUSTFLAGS="%{rustflags}"
export RUSTFLAGS="-C link-arg=-Wl,-z,relro,-z,now"
cargo pgrx package --pg-config ${PG_CONFIG} --features "pg%{pgmajorversion}" --profile release

%install
# Clean buildroot
rm -rf %{buildroot}

# Set PostgreSQL environment
export PG_CONFIG=%{pginstdir}/bin/pg_config
export PATH=%{pginstdir}/bin:$PATH

# Create necessary directories in BuildRoot
mkdir -p %{buildroot}%{pginstdir}/lib
mkdir -p %{buildroot}%{pginstdir}/share/extension
mkdir -p %{buildroot}%{_datadir}/pgsql/password_profile

# Define the source path generated by pgrx
# Note the addition of the slash before %{pginstdir}
PGRX_SOURCE="target/release/%{sname}-pg%{pgmajorversion}"

# Copy extension files
# We use -p to preserve timestamps and avoid quoting the wildcard *
cp -p ${PGRX_SOURCE}%{pginstdir}/lib/*.so %{buildroot}%{pginstdir}/lib/
cp -p ${PGRX_SOURCE}%{pginstdir}/share/extension/*.control %{buildroot}%{pginstdir}/share/extension/
cp -p ${PGRX_SOURCE}%{pginstdir}/share/extension/*.sql %{buildroot}%{pginstdir}/share/extension/

# Copy blacklist file
if [ -f blacklist.txt ]; then
    install -D -m 644 blacklist.txt \
        %{buildroot}%{_datadir}/pgsql/password_profile/blacklist.txt
fi

%post
echo ""
echo "======================================================================"
echo "  password_profile extension has been installed"
echo "======================================================================"
echo ""
echo "IMPORTANT: Post-installation steps required:"
echo ""
echo "1. Copy blacklist file to PostgreSQL data directory:"
echo "   sudo cp %{_datadir}/pgsql/password_profile/blacklist.txt \\"
echo "       /var/lib/pgsql/%{pgmajorversion}/data/password_profile_blacklist.txt"
echo "   sudo chown postgres:postgres \\"
echo "       /var/lib/pgsql/%{pgmajorversion}/data/password_profile_blacklist.txt"
echo ""
echo "2. Add to postgresql.conf:"
echo "   shared_preload_libraries = '%{sname}'"
echo ""
echo "3. Restart PostgreSQL:"
echo "   sudo systemctl restart postgresql-%{pgmajorversion}"
echo ""
echo "4. Create extension in your database:"
echo "   CREATE EXTENSION password_profile;"
echo ""
echo "======================================================================"
echo ""

%preun
if [ $1 -eq 0 ]; then
    echo ""
    echo "IMPORTANT: Before uninstalling, ensure you:"
    echo "1. Remove '%{sname}' from shared_preload_libraries in postgresql.conf"
    echo "2. Drop the extension from all databases:"
    echo "   DROP EXTENSION IF EXISTS password_profile CASCADE;"
    echo "3. Restart PostgreSQL after uninstallation"
    echo ""
fi

%postun
if [ $1 -eq 0 ]; then
    echo ""
    echo "Remember to restart PostgreSQL:"
    echo "  sudo systemctl restart postgresql-%{pgmajorversion}"
    echo ""
fi

%files
# Documentation
%doc README.md
%license LICENSE

# Extension library
%{pginstdir}/lib/%{sname}.so

# Extension control and SQL files
%{pginstdir}/share/extension/%{sname}.control
%{pginstdir}/share/extension/%{sname}--*.sql

# Blacklist file
%{_datadir}/pgsql/password_profile/blacklist.txt

%changelog
* Tue Jan 13 2026 Özgür <ozgur.yuksel@bisoft.com.tr> - 0.0.0-1
- Initial RPM package for PostgreSQL 17
- Rust-based extension using pgrx framework
- Built for RHEL 9 / Rocky Linux 9
- Added comprehensive post-install instructions
- Included password blacklist file

* Mon Jan 12 2026 Özgür <ozgur.yuksel@bisoft.com.tr> - 0.0.0-1
- Pre-release testing version
