EXTENSION = password_profile
MODULES   = password_profile
DATA      = password_profile--1.0.sql
# CONTROL line removed.

PG_CONFIG = /usr/pgsql-16/bin/pg_config
PGXS      := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
